import "./globals.css";
import type { Metadata } from "next";
import { Abril_Fatface } from "next/font/google";

// Abril Fatface만 next/font로 최적화
const abrilFatface = Abril_Fatface({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "SSU PotoPorio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko" className={abrilFatface.className}>
      <body>{children}</body>
    </html>
  );
}
